### PR TITLE
Topic/fusion 22

### PR DESCRIPTION
**Pull request by akamimoor**
## JIRA ticket
[FUSION-22](https://janrain.atlassian.net/browse/FUSION-22)

## Changes

- Added the additional logout methods to the iOS Objective-C app.
- [Google Doc](https://docs.google.com/document/d/1APEXwnAVBdPrTl9ZEeIU9aqQdzdvfk3kmCuWe2Kc-P0/edit?usp=sharing) with test cases

Confluence doc for development instructions: [Here](https://janrain.atlassian.net/l/cp/wqc2506v)

### CODE REVIEW

**Review by schaeferCode — COMMENTED** [review]
Not sure of the expected behavior, but revoke tokens and logout app session doesn't end my gizmo session, which is what I would've expected. If I revoke tokens, then I can just simply refresh my tokens, or check browser session, etc and it all works. I would've expected the need to log back into gizmo. Same thing with app session. Ending the browser session seems to be the only thing that actually ends my gizmo session. 

I could totally be failing to understand the expected behavior here.

**Comment by akamimoor** [comment]
@schaeferCode that is the expected behavior. It is designed that way so that the developer can see the lifecycle of their logout choices. It's unlikely that the developer wouldn't log the user out of the browser, but they have the option to not, and that is what I am showing.

**Review by kreese-akamai — COMMENTED** [review]
Tested all logout scenarios 👍 
The final expected outcome for scenarios 6 and 7 do not return any data about the token when browser is closed.

Six expected: redirected to the initial app login screen
Six actual: redirected back to the previous app screen (does not end app session)

Seven expected: app text should display that no tokens were returned
Seven actual: app text is not updated

**Review by schaeferCode — APPROVED** [review]
Worked for me!

**Review by kreese-akamai — APPROVED** [review]
followed set-up instructions 🟢 
verified all seven scenarios 🟢 
🚀 🌔

**Pull request merged**
