### PR TITLE
[FUSION-297] Finished the Dashboard ViewModel and ViewController

### PR DESCRIPTION
**Pull request by akamimoor**
## JIRA ticket
[FUSION-#](https://janrain.atlassian.net/browse/FUSION-#)

## Changes

- Finished building the ViewController and ViewModel for the Dashboard
- Integrated the Authenticator and coordinators

## Testing

- Set breakpoints inside the sut method being tested. This makes sure the primary method being tested has been called.
- - Example: Set a breakpoint inside the AuthenticatorTests for the testDiscoveryConfigLoaded method by clicking line number 77, which should be the completion handler for getDiscoveryConfigWithCompletion.
- - Breakpoints: To set a breakpoint in Xcode, click the line number to the left of the code.

Update AppAuth-iOS SDK:
`carthage update --use-xcframeworks --platform iOS`

Confluence doc for development instructions: [Here](https://janrain.atlassian.net/l/cp/wqc2506v)

### CODE REVIEW

**Review by kreese-akamai — COMMENTED** [review]
🟢 code changes look good
🟢 simulator run builds successfully
🟢 manual testing in simulator as expected
❓ ~~test build fails~~ 🆗 resolved

**Comment by kreese-akamai** [comment]
Xcode Product Test 
Example.xcodeproj ExampleTests AuthenticatorTests.m issues
Screenshot 2024-02-01 at 9 57 52 AM

**Comment by akamimoor** [comment]
> Xcode Product Test Example.xcodeproj ExampleTests AuthenticatorTests.m issues Screenshot 2024-02-01 at 9 57 52 AM

I'm looking into it

**Comment by kathleen-janrain** [comment]
Hmm I ran the tests Product -> Tests and they passed for me. Maybe I'm doing something different though
Screenshot 2024-02-01 at 13 31 39

**Comment by jbush-janrain** [comment]
Adding another perspective, I'm seeing similar errors as Kevin.  Trying a few tweaks to see if I can get the failing tests passing.

image

**Comment by kreese-akamai** [comment]
✅ All tests passing
 
Screenshot 2024-02-07 at 5 19 02 PM

**Review by kreese-akamai — APPROVED** [review]
build succeeds
manual testing performs as expected
automated test run passing
LGTM 🖼️

**Comment by kreese-akamai** [comment]
❇️  re-ran tests with breakpoint on _Example-iOS_ObjC-Carthage_
✳️  manual testing looks good on _Example-iOS_ObjC-Carthage_
✅  also verified running tests in _Example-iOS_Swift-Carthage_

**Review by jbush-janrain — APPROVED** [review]
After running a `Clean` on the project (shift + CMD + K), build and tests are now succeeding 🎉 
image

🚢 🇮🇹

**Review by kathleen-janrain — APPROVED** [review]
Looked over the code changes (whatever good that's worth ;) ) 
Build succeeded for both Obj-C and Swift Carthage Example projects ✅ 
Ran unit tests for both Obj-C and Swift (with breakpoint in Obj-C)  ✅ 

Looks good to me! Thanks for all of the help getting my environment up and running 🌟

**Pull request merged**
